### ISSUE TITLE
show Clusters in the LEFT sidebar (NOT in topbar)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#102]
why are IFS0 and IFS1 shown in TOP?
We talked about to move the Clusterlist to the (still empty) SIDEBAR...

**Comment by haschimoto** [comment]
so basically THIS:
![snap 2017-06-13 at 00 35 24](https://user-images.githubusercontent.com/20817185/27058215-43e6d20e-4fd0-11e7-9c05-83da2a75a467.png)

goes here:
![snap 2017-06-13 at 00 35 35](https://user-images.githubusercontent.com/20817185/27058217-47d9bfde-4fd0-11e7-8cbe-cafd32ec6173.png)

**Comment by dnelband** [comment]
sorry, i misheard and thought "sitebar" instead of "sidebar", now its fixed
