### ISSUE TITLE
time added in browse is different than time added in detail

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#106]
browse: 3 months:
![snap 2017-06-19 at 14 30 24](https://user-images.githubusercontent.com/20817185/27285129-dbc1a416-54fb-11e7-984e-a1f4d3cae996.png)

detail: 2 months:
![snap 2017-06-19 at 14 29 04](https://user-images.githubusercontent.com/20817185/27285086-b8bd4c18-54fb-11e7-95ff-7c91ae2ceb84.png)

**Comment by dnelband** [comment]
it was two different items which contained the same file, i've deleted the former.
