### ISSUE TITLE
IFS LOCAL: video: doesnt download the file until end, but stops quickly and tries to display the video right away

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#107]
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_19nEWFATQHGZNFsmn8PDEGdJVaH5Byw1jc_5+type:video

**Comment by haschimoto** [comment]
i think i have an idea:
i was not able to download because of the general limit for files on the 0net startpage.
I increased the filesize and now i should have enough space left, but IFS doesnt check and redownload the actual file?
In the folder of the cluster there is no file yet, only this entry in the data.json:
![snap 2017-07-09 at 09 40 27](https://user-images.githubusercontent.com/20817185/27992055-ba5aff0e-648a-11e7-9f11-4e136e383862.png)

**Comment by dnelband** [comment]
i have the file but its 1.9 mb but on the IFS page is written that the file is 60.2 mb, so i think the user didnt stay online long enough for it to be published, but i keep on looking for the reason so i leave that open

**Comment by haschimoto** [comment]
same for this file (it loads and immediately stops loading and tries to play the file):
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1DhiJwjm278k82xAwrRfbLTqYZWjKiCMDt_1+type:video

**Comment by haschimoto** [comment]
not done, e.g. here:
https://fuckcf.cf/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1MEqso53FzGtN3NRYPuDBBbNbP2tUFiR82_4+type:video

**Comment by dnelband** [comment]
1 - tested with two local clients, the file doesnt exist in the user directory (you can check by navigating to the path that stated in "embed url". item / file is listed in content.json / data.json, but wasnt fully seeded by uploader so its not available
2 - this file is above 60mb so as of the latest update it wont be downloaded until BFS is implemented (please see ticket #134 )

**Comment by haschimoto** [comment]
Isnt optional files regardless of size?
Which update was that changed?

**Comment by dnelband** [comment]
tamas told me that in general it wasnt supposed to be able to download such large files (like we have for example videos of 250mb) but we made it work until now anyway, since at least the latest update it is now strictly limited to 10mb and lower, until the big file support is implemented. so it used to work but now it doesnt

**Comment by haschimoto** [comment]
Can you implement BFS with the old files?

**Comment by dnelband** [comment]
here is the message tamas replied to me:

hi

> currently, its not possible to download files bigger the 10mb in zeronet right?
Yes, currently files larger than 10MB will not be downloaded

> would big files that were uploaded before the big file support implementation would be shared or do files need to be written in a specific way for it to work?

It requires per piece (1MB by default) hashing, so users will need to
re-upload the files using the bigfile method.

I'm currently rolling out the feature. The code is already on github,
the demo site (ZeroUp), the improved ZeroHello, documentation,
changelog will follow soon.

**Comment by dnelband** [comment]
how should we proceed? should i put an info message that currently files over 10mb would not be shared? should we restrict size until we impllemented the BFS?

**Comment by haschimoto** [comment]
Can you check out the code and see how to change upload and download for
IFS?

**Comment by dnelband** [comment]
He still hasn’t released the API to use,  im waiting on him to, as soon as it’s available to use i will implement it
