### ISSUE TITLE
Idea: Polish Filestorage Channel View GUI

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#114]
maybe make it look a bit more modern?
e.g. (just an example, dont care for the color green :)
![687474703a2f2f692e696d6775722e636f6d2f69486f47716f4c2e706e67](https://user-images.githubusercontent.com/20817185/29960302-65445272-8efb-11e7-886b-010248dee398.png)

**Comment by dnelband** [comment]
yeah looks great!!

**Comment by dnelband** [comment]
what do you think? should i modernize the rest as well?

**Comment by haschimoto** [comment]
Sure. Just see that the responsiveness always has priority over looks.

**Comment by dnelband** [comment]
hi clemens, ive changed the front page layout, ive tried to make it a bit more like archive.org and modern, i think it looks more accessible like this. let me know what you think, im still working on the responsive cases

**Comment by haschimoto** [comment]
nice, lets revamp the sidebar as discussed , ill close here.
