### ISSUE TITLE
Filesname chars STILL NOT correct and therefore displaying fails?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#117]
Maybe its due to this filename has a "bad" french letter "c" with that stupid hyphen below?
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1DhiJwjm278k82xAwrRfbLTqYZWjKiCMDt_1+type:video

**Comment by haschimoto** [comment]
and yet AGAIN there is now a "~" AT THE END of the filename (as visible per embed code), which is the cause of not loading?
https://fuckcf.cf/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1PjC5pb1Weqj8un9SLpQnqgGrxa6mLdxLE_10+type:game

@dnelband : you NEED to make SURE that you test the F...CK out of EACH TICKET and dont just "ready" them, this is really annoying going through all of these issues again and again.

**Comment by dnelband** [comment]
still testing different kinds of characters to make sure its done, will mark as done when im sure i didnt miss anything
