### ISSUE TITLE
Video: File loads, then ALWAYS says its not cached instead of playing it! "Browser Reload" the page immediately shows the video ready to play, so it is IN CACHE already.

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#127]
first its loading:
![snap 2017-10-01 at 17 23 56](https://user-images.githubusercontent.com/20817185/31056167-dc616144-a6cd-11e7-8d4a-c4141d510f8a.png)

then NEVER comes up playing it, but says not available:
![snap 2017-10-01 at 17 26 38](https://user-images.githubusercontent.com/20817185/31056177-ef4acfca-a6cd-11e7-8b2e-bc7f0f88730e.png)

a simple site refresh shows it is in cache loaded and plays it.

**Comment by haschimoto** [comment]
easily testable with many videos not in cache here:
https://fuckcf.cf/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/

**Comment by dnelband** [comment]
i've tested with fuckcf.cf two videos, one above 10mb & only 1.5mb, the one above 10mb repeatedly tried to download but didn't play the video, explanation to this is in this ticket #134 , the one blow downloaded & played it immediately. i'm not sure exactly what happens to you user - after initial view it downloads, then fails to play, then on refresh plays the video? its just the title change of the ticket confused me
