### ISSUE TITLE
[idea]: avoid confirming / adding 1 site per load first time: grant access in one swoop to avoid error messages

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#13]
- is there a way to grant access and load all channels in one swoop, so a new visitor of IFS doesnt get any error messages or the need to refresh and grant access multiple times before the site appears working  smoothly?
to avoid something like this:
![2017-01-18 18 21 08](https://cloud.githubusercontent.com/assets/426427/22069872/01c25700-ddab-11e6-9072-c64e19da4300.png)

**Comment by dnelband** [comment]
Tamas's answer: there is no way to add "all" sites and adding new sites are
rate-limited, so you should not add it blindly, but based on
user-interaction.

**Comment by haschimoto** [comment]
"new sites are rate-limited, so you should not add it blindly, but based on user-interaction."

I dont understand a word.
Anyway, we need a way to not have any error messages, but automatically have all sites added before the error messages appear... like an "initializiation or loading" page once a new user loads the master site for the first time.

**Comment by dnelband** [comment]
Tamas says thats its not possible to add all sites in one action and that user must approve sites individually. I.e no way to avoid adding 1 site at a tine. His logic behind it is that user should only add sites he wants. Should i write hin that we need this?

**Comment by star-buck** [comment]
yes, we need a method that allows to skip manually confirmation.
It should ask to grant access once and then be done.
