### ISSUE TITLE
IFS2.0: audio/video page: show JS-Player right away instead of "file not found", then while downloading allow start playing the video like on zite "ZeroUP" even if partitially downloaded yet

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#136]
- treat all uploaded files as BIG FILES, even those below 10mb if possible
- treat all Big Files as optional

**Comment by dnelband** [comment]
im implementing it,  but testing it will take a bit of time because it involves uploading / deleteing big files multiple times. i'll update

**Comment by dnelband** [comment]
video / audio file plays as soon as there are chunks available (i.e as soon as there is 1% percent or more, reflected in the File API of zeronet) but still missing visual feedback (i.e live information about how much is downloaded etc'). working on it
