### ISSUE TITLE
IFS 2.0 Big Update

### ISSUE THREAD

**Issue by dnelband** [zer0net/ifs-master#139]
In Short
- changed the js framework from angular.js to react.js due to zeronet compatibility & performance issues. Improved loading time & behavior 
- redesign the website (based on existing structure) for a more user friendly experience .

General
- Cached (green item) status is determined by the item’s “is_downloaded” attribute , which ZeroNet sets to true even if only one byte has been downloaded.  To bypass that problem ,we use the is_downloading attributes (which indicates activity ) and the number of pieces (chunks) that file has in cache to determine its status. If it is downloading & the number of chunks is higher then 1 then its in cache , because this state usually means that the file is seeded enough . If its downloading but only 1 chunk in cache theres a chance that its not  seeded enough & wouldn’t be viewable to user. Same case If the file has more then one piece but is not  is_downloading. I would still say that the different play with the variables is still in testing , but it seems to work good & be precise 

Item view
- if item is not cached zeronet will try to download it
- if initial response takes too long (> 15sec) show “warning” message. If file has some pieces available show an option to play partial file (if file is audio/video/image)
- if download “is active “ (i.e an additional chunk has been downloaded ) it will play the file if it is possible to play a partial file of that content_type
- if download fails show error message (with a buttoon to play partial file if exists & possible )

User View
- now user view content updates on zeronet certification change (no reload necessary)
- on user channel edit / new channel forms are rendered in a view (not popup window) - for your review, in my opinion it feels better like that
 - Upload logo / poster image on the fly (channel form, item edit form)

**Comment by haschimoto** [comment]
Absolute Fantastic update!
Still closing this here for single items.
