### ISSUE TITLE
IFS 2.0 Notes / Thoughts / Suggestions

### ISSUE THREAD

**Issue by dnelband** [zer0net/ifs-master#141]
**categories** - it feels a bit useless as it currently is since main categories are the same as content_types 1:1. It would be much better imo to remove these categories & create a category tree for every content_type, for example in games the different categories will be consoles & subcategories would be generes. Then in every content type view on the main page we can filter its items by its own categories 

**option to participate in content shaping**- i think some aspect of participation would be a great addition both for development & user experience, for example an option to specify new categories on file upload: user will create new category which will have to be authorized by admin. If category is authorised item will be automatically assigned to it. If not item will be categorized as misc.

**notifications** - without user interaction the site feels dead, so i think it would be an improvement to add notifications for  comments / votes on users items, that will increase usage of the site in my opinion. 

DONT**Counting Views** - Going a bit further, counting an item “views” could be another thing to give the site a more lively feeling. We can also do that in a way that the users content.json would not be updated on “view” action, and only if they perform another action (which results in user-content publishing) would the “views” information be published

**Comment by haschimoto** [comment]
lets not implement "Counting Views" for now. Peers is the only relevant measure.
