### ISSUE TITLE
Clicking a file first time always shows full green bar, thats misleading.

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#147]
I guess you changed it for single files below 1 MB, but still its misleading for all files now.
Especially when you use ZN * TOR, you get stuck on a full green bar while the video refuses to play as its not yet connected to peers, downloaded the piecemap or whatever reason...while it looks like its all green.

**Comment by haschimoto** [comment]
This song as example:
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1_1KMBUmz57LumMsDZfoZJkzZhXC6FVcZrik_2+type:audio
![snap 2018-01-20 at 07 55 57](https://user-images.githubusercontent.com/20817185/35180798-6712255e-fdb7-11e7-8ea8-2c17df371120.png)
![snap 2018-01-20 at 07 56 07](https://user-images.githubusercontent.com/20817185/35180800-69f3becc-fdb7-11e7-9bbf-36d53c6e9b38.png)
It never loads, but still shows all green and 49 peers.
(Dont confuse with someone re-uploading the same song visible in the sidebar, this is the 5 months old upload not working).
I guess what happens is the file would take some short time to download as its not a BFS yet, but one chunk, but since the bar is ALWAYS green from the beginning, and never changes, its whats misleading.

The correct way would be to show a grey bar and only make it fully green for NON-BFs if its fully cached/downloaded.

**Comment by dnelband** [comment]
i have both the mika's, now the bfs one shows all bars green, the pre-bfs one show a full green line if the file is downloaded fully (i.e, "is_downloaded" attribute from the zeronet optional file api), but pre bfs that are not fully downloaded (or nothing at all) will show a gray bar, tested with the deadmau5 file. please check if it works for you as well
