### ISSUE TITLE
Video JS Player: Really hard to skip video, as clicking one pixel over or under the exakt middle of the video timeline does nothing

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#148]

**Comment by dnelband** [comment]
ive added an effect which resizes the progress bar on hover to 10px height, now its easier to click, let me know if the size is ok

**Comment by star-buck** [comment]
how can this work on mobile when there is no hover?
please make it bigger overall like 1up with no hover.

**Comment by haschimoto** [comment]
how can this work on mobile when there is no hover?
please make it bigger overall like 1up with no hover.

**Comment by dnelband** [comment]
ok now its permanently bigger, is the size ok?

**Comment by haschimoto** [comment]
okay.
