### ISSUE TITLE
[clone]: newly cloned channel should be auto-renamed with newly created site hash

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#15]
if possible use site hash for new name instead of "myfilehub master",
it looks cool and gives some sector/cluster feel :)

**Comment by siyuandong** [comment]
there is no possibility to change title while clone site.  and after clone needs user interaction for changing title.
I added a template-new directory for clone filehub channel.
Page.cmd("siteClone", ["1CG6obEGoFL1fjAoNaxUnemgKES7Zh9YBG", "template-new"]);		

reference to 
https://github.com/HelloZeroNet/ZeroNet/blob/master/src/Ui/UiWebsocket.py line 702
