### ISSUE TITLE
When accessing site: "Waiting for fonts.googleapi.com" :/

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#150]

**Comment by stbinan** [comment]
@haschimoto good catch. @dnelband please delete `./assets/lib/semantic-ui/semantic.min.css:11:@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin);` and add the related source locally.

**Comment by dnelband** [comment]
to have the fonts locally would cost us in mb, should i try to implement the minimal font locally (2mb at the least) or should i just use a generic font?

**Comment by star-buck** [comment]
try a generic font.

**Comment by haschimoto** [comment]
try a generic font.

**Comment by dnelband** [comment]
using arial, does it look ok for you?

**Comment by haschimoto** [comment]
looks fine.
