### ISSUE TITLE
Piecemap: Distinct loaded, not loaded, or not even there: Show some info overlay AND always show the file chunks row with some info there

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#154]
First time clicking a Big File like Video shows this:
![snap 2018-02-27 at 23 04 17](https://user-images.githubusercontent.com/20817185/36757801-c5f2aa70-1c12-11e8-8d82-daab382bc4aa.png)

Even if showing 2 peers, it does not show any chunk information, while it seems not having the piecemap yet.

If one waits long enough (like 1-2 minutes some times), it does start to show the pieces loading bar and the video starts to autoplay:
![snap 2018-02-27 at 23 07 12](https://user-images.githubusercontent.com/20817185/36757924-0f29cca0-1c13-11e8-8c48-f76e7f2ddb9f.png)

In the meantime until that happens, I suggest instead of showing the PLAY button on black screen only, display some overlay on that video like "Fetching Video Information, that can take a while" and have something spinning, so it doesnt look lifeless...

**Comment by haschimoto** [comment]
after a complete reload, the page looks different, now showing the EXTRA file chunks info ROW:
![snap 2018-02-27 at 23 10 41](https://user-images.githubusercontent.com/20817185/36758065-8a838f6c-1c13-11e8-970e-14777e7935a2.png)

Maybe the first time when there is no piecemap yet, it should STILL SHOW THE ROW under size and say:
"Fetching piecemap information..." with the "..." animated and if possible updating that row to "FETCHED" and then replacing it with the chunk information without reloading the whole page.

**Comment by dnelband** [comment]
is this solution good? i've placed it between the chunk info bar and the media player

**Comment by haschimoto** [comment]
please ALWAYS show the "file chunks" row.
Then you need to check if it even makes sense, like if the file is SUPERSMALL or even OLD so it doesnt have piecemap... then just show the ROW STILL ALWAYS, but if piecmap is loaded show that or if no piecemap needed, show "single file" or something instead.

currently it looks like this, which is wrong:
![snap 2018-03-05 at 14 46 37](https://user-images.githubusercontent.com/20817185/36978317-5e778570-2084-11e8-95c4-43e6083353b9.png)

**Comment by haschimoto** [comment]
already has the piecemap(?), but still shows it is loading the piecemap instead of loading first chunk:
![snap 2018-03-05 at 14 55 01](https://user-images.githubusercontent.com/20817185/36978621-40ea667a-2085-11e8-91f8-88bbb2e160a2.png)

**Comment by haschimoto** [comment]
![snap 2018-03-05 at 14 56 27](https://user-images.githubusercontent.com/20817185/36978675-6be819e4-2085-11e8-9c44-fd6c321bb1d9.png)

**Comment by dnelband** [comment]
1 - try to update the site because the "fetching piecemap information" shouldn't appear in item's with non big files / items with pieces loaded, i've signed + published a couple of times again.
2 - so instead of removing that line it should be replaced with "piecemap ready" or "single file" where there are no chunks? i'm not sure i understood what you meant
