### ISSUE TITLE
loading emulator forever...

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#157]
![snap 2018-03-07 at 21 09 05](https://user-images.githubusercontent.com/20817185/37115597-d4961e1a-224b-11e8-86ed-7c080907b27f.png)
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1_1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp_item_166+type:game

**Comment by dnelband** [comment]
Im currently working on the emulators, its only temporary

**Comment by haschimoto** [comment]
okay, i also noticed for amstrad fruity frank that i cannot control them via keybaord like it wwas possible before... normally it had the arrow keys working or ASDW, but now it seems totally weird...

**Comment by dnelband** [comment]
Im currently solving the zip issue (i.e games in a zip archive that are not
dos) and it probably breaks some things, i will finish this issue and then
make sure everything is functional

**Comment by dnelband** [comment]
![screen shot 2018-03-08 at 13 34 42](https://user-images.githubusercontent.com/5212537/37151391-9caff57c-22d5-11e8-9046-c36b331898ab.png)
after you fail you get to this screen which shows the controls

**Comment by dnelband** [comment]
i dont understand why its using this weird keyboard mapping

**Comment by star-buck** [comment]
i am sure it was different before...
