### ISSUE TITLE
Single FILE for new 33MB?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#160]
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1Mz1_1G27nKed7YQPtNxhH7DXoEKkmjj7Yq5D1x_item_4+type:video
![snap 2018-03-08 at 18 02 02](https://user-images.githubusercontent.com/20817185/37164547-e795b624-22fa-11e8-8fdc-5bad5b0a35c1.png)

**Comment by haschimoto** [comment]
after 15 seconds it then switched to piecemap and then started downloading chunks...
but it still DOESNT show the ROW with chunks.... it should ALWAYS SHOW the row, even if there is a "?" or simply empty info at first load ever....
![snap 2018-03-08 at 18 03 41](https://user-images.githubusercontent.com/20817185/37164621-1fbf2224-22fb-11e8-9487-e1ef8a2fdc4f.png)

**Comment by haschimoto** [comment]
but it still DOESNT show the ROW with chunks.... it should ALWAYS SHOW the row, even if there is a "?" or simply empty info at first load ever....
![snap 2018-03-08 at 18 03 41](https://user-images.githubusercontent.com/20817185/37164621-1fbf2224-22fb-11e8-9487-e1ef8a2fdc4f.png)

**Comment by dnelband** [comment]
i see, it doesnt update live, previously when you mentioned "row with chunks" i thought you meant the row with the green / red chunks. im on it

**Comment by haschimoto** [comment]
i meant the text row directly under "size" should always be shown.
If you know its a single file, then show that info, if you know its a BF, then show the expected chunks or something useful, but always show that text row so the user knows it exists.

It is absolutely bad stlye to hide lines or rows or whatever like MS OFfice did do at some point and then reveal it for some reason because it frustrates users that sometimes it is there, sometimes not, its irritating as hell....

**Comment by dnelband** [comment]
ok, now if it has some kind of pieces info it will show "?" until new info is recieved, if it doesnt it means its a single file, so it will have "single file" there. on initial load it will show the existing piece information , and then will update with new chunks downloaded
