### ISSUE TITLE
Download link (below thumb up icon) doesn't appear before the file is downloaded

### ISSUE THREAD

**Issue by stbinan** [zer0net/ifs-master#163]
It may be better that download link is always available. For example for book downloading, without the download link, a user can't easily find a way to download the book: [case](zero://Me.ZeroNetwork.bit/?Post/1oranGeS2xsKZ4jVsu9SVttzgkYXu4k9v/1AWwhg4EiWAVttfQboJZ4wJfX3WawfJT3h/1521000562)

**Comment by dnelband** [comment]
if the file is not downloaded by zeronet it cant be downloaded because then the user will download a partial file that will not work in most case

**Comment by stbinan** [comment]
@dnelband then the solution will become adding a pin (or +seed like ZeroUp) button for book downloading page, or there is a weird bug need to figure out.

My experience: if I don't log into IFS, the download process animation (aka the one under a video) doesn't show up. After I log in, the animation is stuck in the first block and doesn't move on. But when I use the download link inside "Embed Code", I can successfully download the book.
