### ISSUE TITLE
After upload, it says: Content signing failed 'sha512'

### ISSUE THREAD

**Issue by slrslr** [zer0net/ifs-master#164]
I have tried to upload new .webm video to my channel at [IFS zite](http://127.0.0.1:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er) and it said:

 Content signing failed 'sha512'

The Firefox console shown following errors:

unreachable code after return statement[Learn More]
js-dos.js:178:6

Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
react-dom.js:18238:8

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:43110/ZeroNet-Internal/BigfileUpload?upload_nonce=removedFOrPrivacy?. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
react-dom.js:18238:8

unreachable code after return statement[Learn More]
js-dos.js:178:6

-------
When i open the file in IFS to play it, it says: "failed to download file. it probably doesn't have peers , or the file is curropted. please try again later"

.mp4 and .avi also fails

**Comment by dnelband** [comment]
could not reproduce, just upload this file types without a problem. does it happen with every file type? is the upload process complete i.e redirects you to the channel dashboard or does it remain stuck on the file upload view?

**Comment by slrslr** [comment]
@dnelband Hi, yes, every file type i tried fails, [here is the video](https://mega.nz/#!t58nGLIA!z4R9n855we0IXsw6NdccUHu7J912SwDPgv3vtNVHc_0).
This error appears not only on Firefox, but also on Tor browser where new IFS account was created for me and new channel. Example this video fails with sha 512 error: [here](https://mega.nz/#!dkUx3IrB!Ksf1Xp4P_4cEWmTimXcMvqDAZkoUHWyuTA0XAzMITVE)
btw: it is not zeronet problem, because other video that also give sha512 error was successfully upload on kopykate zite.

**Comment by dnelband** [comment]
@slrslr ok, thanks for the video!
i've created a new account on a new client but still can't reproduce the problem, 
are you able to vote / comment on items? or does it give you the content signed message as well?
i see you have another channel, does upload anything to it works?

**Comment by dnelband** [comment]
i see that you've just uploaded an mp4 called "anti polution etc'" but only on the content.json / as a pieace map, i dont see it in your data.json

**Comment by dnelband** [comment]
@slrslr please test again, i've pushed a possible solution

**Comment by slrslr** [comment]
Publishing comment, voting (tried other people videos) and deleting sha512 errored video is OK, because it says: Content published to 5/5 peers.
BUT when i open the video on IFS main page and vote it or add comment, it says "Content signing failed
'sha512'", i see comment was added on my side, but unsure if others see it. Check IFS main page, there may be test video sha512.

UPDATE: i will try , thank you

**Comment by slrslr** [comment]
@dnelband i tried to upload again, and the same error (sha512) and similar developer console errors like ones i mentioned in my first post here. Please let me know if you need anything else to debug it.

**Comment by dnelband** [comment]
@slrslr i'm working on possible solution and will update here when it's time for testing, i've never experienced this error & see no documentation so its a bit less straight forward, but thank you for your support.

**Comment by dnelband** [comment]
@slrslr please test when possible, i tried another solution (i apologize for the back & forth but due to the fact that it does'nt happen to me im a bit blind here). if it works great, if it doesnt:
1 - find your user directory, its ZERONET_DIR/data/1MzV32sv55VSD5Vr7u3mcMPsX2oG9PHusr/data/users/XXXX
2 - check the content.json file, under files_optional, and compare with the files in the folder. is there something missing from one that appears in the other?
3 - try to delete the not working files that dont appear in content / data json, and retry the upload

**Comment by dnelband** [comment]
btw i can see your comments on other uploaded items. i think the problem is that the uploaded items are not listed in data.json. please make sure its updated before testing

**Comment by slrslr** [comment]
@dnelband

please kindly remove user identifier/hash/public key from your previous comment for privacy.
I tried to upload file and error is still there. So i followed your instructions from your previous post and found that the user directory contains file/s that i deleted on IFS page. The non working files has .msgpack extension, not real video extension and in content.json they have sha512 and size variable set...
It do not appears any are missing, it is 11 entries in content.json and 11 files

>  apologize for the back & forth

no problem, i will be happy if i can help in fixing the issue

**Comment by dnelband** [comment]
do you see the newly uploaded file in your data.json under items?

**Comment by slrslr** [comment]
@dnelband Thank You, no, new videos i tried to upload (that returned sha512 error) are not in data.json ... (only old ones are there)

**Comment by Tvax** [comment]
I'm experiencing the same issue, I tried to get my data but I couldn't find my directory in data/1MzV32sv55VSD5Vr7u3mcMPsX2oG9PHusr/data/users/

**Comment by dnelband** [comment]
hi @slrslr, i've added more console logs to the download process that might shed more light on the issue, please update the site, try to upload again, copy everything in your console.log and paste it here

**Comment by slrslr** [comment]
@dnelband 

Hi, i just updated site, refreshed and uploaded file again, and error sha512 is there and here is Firefox dev. console full output: https://defuse.ca/b/OA0aQLn0sw5o4sVVAMGKyS (password: ifs) please let me know if i can do anything else.

**Comment by dnelband** [comment]
@slrslr 
please update zeronet to Rev3370, and then upload a file again, this time you should get a more detailed error message, copy it & paste it here. in case you dont get anything other then "sha512", please try to search the corresponding log in the zeronet error.log

**Comment by slrslr** [comment]
@dnelband Thank You, i just updated and tried again and upload worked. It seems IFS system was good, but [zeronet itself was not](https://github.com/HelloZeroNet/ZeroNet/issues/1339).
