### ISSUE TITLE
Can not delete some files that failed uploading: "Loading User Files"

### ISSUE THREAD

**Issue by slrslr** [zer0net/ifs-master#166]
Hello,

before a month maybe i created channel (at cluster 0), i uploaded a few videos, some worked, but some maybe not had right format so it do not play and says: "failed to download file. it probably doesn't have peers , or the file is curropted. please try again later"

But i can not delete these files. When i select to delete it and confirm, it show blank page with text "Loading User Files". Video was not removed, in my zeronet folder it appears to be 1KB and with ".msgpack" extension unlike other videos that succeeded have valid video extension and shows normal size.

This i see in Firefox console:

...
[ZeroWebsocket] Open all.js:143:14
[ZeroChat] Restore scrollTop  Object { scrollTop: 0 }  0 class.js:20:7
unreachable code after return statement[Learn More] js-dos.js:178:6
[Wrapper] Setting title to IFS - ZeroNet all.js:1615:14
[ZeroChat] Websocket callback not found: Object { cmd: "response", to: 11, result: undefined }
class.js:20:7
unreachable code after return statement[Learn More] js-dos.js:178:6
...

I assume this may not be easy to be debugged/fixed, so i wanted to ask what is the easiest way to remove these files from public view and from my channels? Should i try to remove their lines from C:\ZeroNet\data\1MzV32sv55VSD5Vr7u3mcMPsX2oG9PHusr\data\users\myusernameaddress\content.json & data.json ?

**Comment by dnelband** [comment]
the easiest way would be to manually delete the entries from data.json & content.json, and then perform an action which publishes user content (vote, comment, upload etc') to publish changes

**Comment by slrslr** [comment]
@dnelband

Hello, thank you for help. I removed unwanted video files from my user directory on my computer, then removed unwanted file lines from content.json and data.json, but when i do some "like" (like some video on IFS) action on IFS, the content.json is updated with files that no longer exist, which seems wrong.

**How to propagate/synchronize changes made in user's .json files into merger zite**

I figured out, that when i edit .json files and then at ZeroHello find IFS Clusted 0 and 1 merger zites and in its menu "Check files" and then do "like" on IFS site, the .json file gets updated, but deleted files are not added into .json files which is good. So it may be good to take a note of this obstacle in propagating manual changes in .json :-S UPDATE: it do not work always, i am trying to update IFS cluster 1 json file and it gets reseted every time.

Anyway file upload was successful now.

**But when i try to delete it, then i see "Loading User Files" and files are not deleted**, here i pasted Firefox developer console (F12) output: https://defuse.ca/b/PmEe850EAScaIHGmLA2cyw (password: ifs)

**Comment by dnelband** [comment]
hi @slrslr , i'm not sure i understand - are you not able to delete new files you've uploaded?

**Comment by slrslr** [comment]
@dnelband correct (i tried to delete just one file and this file also can not be played, says ""failed to download file. it probably doesn't have peers , or the file is curropted. please try again later""), i pasted link to defuse.ca where are details.

**Comment by dnelband** [comment]
hi @slrslr , i've added some console.log messages to the file delete process, please upload a file and copy all of the logs in the console, then delete a file a copy all the logs in the console, and paste them somewhere together. i suspect that the file is not uploaded to the correct folder, but i cant reproduce the issue

**Comment by slrslr** [comment]
@dnelband i just did that. This is what i saw in the console from time i loaded my channel to the point video was successfully uploaded: https://defuse.ca/b/D9o6f62XVwB6HsSjyA0x5U (password: ifs)
Then i cleared console output and selected to delete the uploaded file and confirmed it, now i see "Loading User Files" and the whole console output is only:
-- delete item -- all.js:8240:5
inner path:merged-CDN/1MzV32sv55VSD5Vr7u3mcMPsX2oG9PHusr/data/users/myusernameaddress all.js:8242:5

**Comment by dnelband** [comment]
@slrslr thanks, 
could you:
1 - update IFS and try deleting again, i've added more console.logs
2 - then try to create a new channel on ifs cluster 1 (not 0) and try to upload / delete there. is it the same?

i've also started experiencing bugs with content signing since the update (Rev3372), so i'm pretty sure its because of that

btw: can you see the new item "stap tap inst"?

**Comment by slrslr** [comment]
@dnelband 

1 - I updated IFS zite and tried to delete the file/video that i uploaded last time (before two hours around) and here is the result: https://defuse.ca/b/DhBpY0kGADXo9ylUJiDGKL (password: ifs)
2 - yes, the problem is also on cluster 1, can not delete, upload is OK :-)

No, i can not see "stap tap inst" on IFS, i tried to search it on main page and also using search field. Site is updated, Cluster 1, 0 on zerohello shows "1 FILE UPDATE FAILED" when i recheck files.

**Comment by dnelband** [comment]
ok it seems that fileDelete function does not respond. i will update as soon as there is a solution implemented. is there some other zeronet Zite on which you can test deleting / uploading?

**Comment by slrslr** [comment]
@dnelband

i just tried to upload video files to ZeroUp and to KopyKate big and deleted them, it apparently succeeded (do not see it on site and content published), but in KopyKate user directory on my computer, the file was not deleted, it is only not visible on site (i tried to recheck files and update both site and its merger).

**Comment by dnelband** [comment]
thanks for the info, i'll update soon

**Comment by dnelband** [comment]
hi @slrslr , does the delete function removes the item from the data.json now? i think the file would still remain because the error persists, but now it should remove the entry from the data.json

**Comment by slrslr** [comment]
@dnelband hi, no, file entries are in data.json, but files itself are not there (was deleted), only 1KB  .msgpack files remaining

**Comment by dnelband** [comment]
currently it looks as though my changes to the site as site owner are not even being published. i will update here as soon as the situation is fixed

**Comment by dnelband** [comment]
ok it seems that some of the content sign errors were resolved, @slrslr could you check if IFS was updated, if it was, could you test delete item again, and tell me what you see in the console? thanks

**Comment by slrslr** [comment]
@dnelband Hi, in ZeroHello menu it says IFS "Updated 19 minutes ago", so i clicked Update, visited IFS page, My channel, selected to delete one of the failed videos that do not play and confirmed delete. [Here is](https://defuse.ca/b/HyvlbN7rWHMbM9sbKAxLs7) dev. console output (password: ifs)

**Comment by slrslr** [comment]
Good news, i see it shown "Loading User Files", but it DELETED the file from my channel! :)

**Comment by dnelband** [comment]
it doesnt return to the channel dashboard? does it load forever?

**Comment by slrslr** [comment]
yes, it loads for ever, but when i open IFS on other tab, i no longer see the video in my channel 👍
