### ISSUE TITLE
File: After completely downloaded, the file seems gone and starts downloading again after refresh

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#167]
downloaded once:
![snap 2018-03-26 at 16 25 08](https://user-images.githubusercontent.com/20817185/37912278-791de9d4-3112-11e8-8306-b6de18315d63.png)

after resfreshing the site:
![snap 2018-03-26 at 16 25 23](https://user-images.githubusercontent.com/20817185/37912291-8246a53c-3112-11e8-9085-74b2ed873d89.png)

it also doesnt appear to be stored in the overview:
![snap 2018-03-26 at 16 27 48](https://user-images.githubusercontent.com/20817185/37912360-aa6c7fa0-3112-11e8-9a80-f4140ebfdb50.png)

**Comment by dnelband** [comment]
fixed, please test, do you see my last update? i got a "content signing failed" on sign & publish but on the error.log it says that it did sign & publish, so im not sure
