### ISSUE TITLE
ZIP: Do no longer associate ZIP=DOSGAMES, but make it new TYPE=ARCHIVE

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#168]
it seems strange, first time click on ZIP it gives ERROR:
![snap 2018-04-02 at 11 22 06](https://user-images.githubusercontent.com/20817185/38191287-6c93a5ea-3668-11e8-80b4-1ce6630fc2b5.png)

then after REFRESH, it thinks it already has 72/73 chunks downloaded, and only needs last chunk:
![snap 2018-04-02 at 11 22 44](https://user-images.githubusercontent.com/20817185/38191309-8523c996-3668-11e8-9baf-2dd82d4237f8.png)

We need to make sure that:

- ZIP files are of new type: ARCHIVE, and not GAME
- make user select how to open ARCHIVE file.
- Default is it can only be downloaded, no VIEWER is associated with ARCHIVE

**Comment by haschimoto** [comment]
for other bookdump, i get this error:
![snap 2018-04-02 at 11 28 48](https://user-images.githubusercontent.com/20817185/38191446-0d1fbe9a-3669-11e8-9d54-42d100b7553f.png)

**Comment by dnelband** [comment]
now there is a new content type - archive, and it has a misc subcategory, we can add subcategories later. it opens or waits for enough information to download in order to show a file list, i need to go over the site and make adjustments to fit this new structure

**Comment by haschimoto** [comment]
okay, the error is still weird though now popping up endlessly every 5 seconds:
![snap 2018-04-06 at 09 09 34](https://user-images.githubusercontent.com/20817185/38407605-7690084e-397a-11e8-907a-6cf43a4cff8b.png)

**Comment by dnelband** [comment]
i've been using the ZeroNet zip reader for this but it's error handling is obviously too annoying to use. i'm looking for another solution / something native.
