### ISSUE TITLE
Item View: Loading: Page doesnt auto-refresh (it doesnt tell you when the piecemap is loaded nor updates the chunks)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#169]
One clicks any new item (single or big file) and the page simply is stuck.
Only after RELOADING the same page you see that it already has fetched the peicemap, then started downloading chunks, etc.

This video, IFS claims its single file:
![snap 2018-04-06 at 09 19 55](https://user-images.githubusercontent.com/20817185/38407961-d3afcfc2-397b-11e8-8088-18c5d8d9b431.png)

it is stuck forever on that display
only when MANUAL refreshing the page, you see it already has fetched a piecemap and started downloading:
![snap 2018-04-06 at 09 20 26](https://user-images.githubusercontent.com/20817185/38408089-527e8316-397c-11e8-9f05-dc52cf30d5d7.png)

then it is stuck on that, it never updates the green piecempa chunks, so again after manual refreshing the page it shows you its already much further in downloading:
![snap 2018-04-06 at 09 22 44](https://user-images.githubusercontent.com/20817185/38408034-1c23353c-397c-11e8-95e0-4f5c173baccc.png)

**Comment by dnelband** [comment]
it seems that when we use the fileNeed zeronet api with the "|all" suffix, the API doesnt update the site, so removing the suffix makes the download info update. it pushes to download everything in both ways, so i will leave it like that. if you see a file that doesnt download fully, it only means that there aren't peers for the chunk. so this ticket is ready
