### ISSUE TITLE
IFS3.0: General Look Ideas

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#171]
cloned IFS for frontend development : 1CLm2ET29VWxF2utb1uzhziBco3fFnnygT
it will use the libraries from 0Libs : 1PwSiyXRti7JnvxdoTGcJHo6H9KWPhwBu3

- black header: move IFS logo in the middle, when hovering put "Intergalactic" on left side and "File Server" on right side
- shrink the whole light blue section by removing the logo there

**Comment by haschimoto** [comment]
https://archive.org/details/animationandcartoons

**Comment by dnelband** [comment]
the cloned IFS for frontend development : 1CLm2ET29VWxF2utb1uzhziBco3fFnnygT
it will use the libraries from 0Libs : 1PwSiyXRti7JnvxdoTGcJHo6H9KWPhwBu3
it is not up yet because i need to set up the CDN connection, i'll update when it works on a test client as well

**Comment by haschimoto** [comment]
ideas:
- filter items via URL, that allows to jump back to e.g. all videos or a certain format and page, but not "ALL"...
- black header: move IFS logo in the middle, when hovering put "Intergalactic" on left side and "File Server" on right side
- shrink the whole light blue section by removing the logo there

**Comment by dnelband** [comment]
is this what you meant? i'll add a dropdown menu on the user icon click if you approve

**Comment by haschimoto** [comment]
this starts to look awesome!
the top bar is great, also the main overview color and smaller filter bar!
