### ISSUE TITLE
IFS: open any itemview inside its own DIV overlay, so then you can easily "close" this and continue exactly where you were before (like channel or filter or search view)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#177]
![snap 2018-04-17 at 14 47 05](https://user-images.githubusercontent.com/20817185/38870676-d6906342-424e-11e8-96be-d2f00e4403f3.png)

![snap 2018-04-17 at 14 47 27 copy](https://user-images.githubusercontent.com/20817185/38870683-dc984ac0-424e-11e8-9084-1147b41dfa2e.jpg)

**Comment by dnelband** [comment]
is this good?

**Comment by haschimoto** [comment]
This was removed with last update?

**Comment by dnelband** [comment]
no, it seems only clicking on the item name would redirect. now everyclick will open a div. but what about the suggested items on the right? should they open in the same overlay?

**Comment by haschimoto** [comment]
That item name click redirect did work, but clicking on the cover stopped
working.
Both now opening div seems not optimal, so can you make it work exactly
like before the reduced size/optional imgs update?

**Comment by haschimoto** [comment]
Clicking on a video item is also different than clicking on a img... video
now always opens div, while img still redirects... this was probably what
let to the confusion... lets make all open the same.
