### ISSUE TITLE
"Big Files" List on Hello Zero Startpage - Files Tab shows IFS Cluster 1 entries that are not on IFS Main page?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#191]
![snap 2018-05-02 at 17 08 18](https://user-images.githubusercontent.com/20817185/39531508-94f31aae-4e2b-11e8-94d2-772a8177632a.png)

**Comment by dnelband** [comment]
i dont see them on my big files table, but i'll leave this ticket open
