### ISSUE TITLE
dosemu: game zip loads, but emulator never shows up...

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#212]
e.g.
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1_1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp_17+type:game

**Comment by haschimoto** [comment]
emulator area shows "loading" on white canvas forever:
![snap 2018-08-04 at 20 10 19](https://user-images.githubusercontent.com/20817185/43679248-7fe57364-9822-11e8-8588-61d70a564066.png)

**Comment by dnelband** [comment]
i fixed it so that the emulator would show up but im getting this error with this game: Emulation aborted due to nested emulation timeout.

i'm working on finding out why and implementing a solution

**Comment by haschimoto** [comment]
seems fixed?

**Comment by dnelband** [comment]
The emulator is running but the game fails to launch, should i leave it for now or try to find a solution?

**Comment by haschimoto** [comment]
for me the game starts fine...

**Comment by haschimoto** [comment]
wow, now for me it also doesnt start anymore... i am absolutely sure it did start fine just a few hours before

**Comment by haschimoto** [comment]
it seems now the mounting fails, but as can be seen in other screenshots, the game did launch fine just before.
Here is the error:
![snap 2018-08-08 at 23 50 44](https://user-images.githubusercontent.com/20817185/43866463-17a3a450-9b66-11e8-94b2-28d2a595e5b5.png)
