### ISSUE TITLE
green progress bar: is visually one chunk behind

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#214]
- when downloading the first chunk, the green progress bar doesnt start
- after downloaded the first chunk, the progress bar shows the first chunk in progress
- after downloaded the second chunk, the progress bar shows the first chunk green and the second in progress
- after all is downloaded, therefore the progress bar is not fully green at the end, but still shows the last chunk in progress

**Comment by haschimoto** [comment]
here is an example:
![snap 2018-08-07 at 21 07 20](https://user-images.githubusercontent.com/20817185/43796919-f25b1cfe-9a85-11e8-8707-95dbf20429f3.png)

all chunks have been downloaded, but display shows 2 green and 1 in progress

this immediatly corrects after refresh, so its only valid for new, previously unclicked files

**Comment by haschimoto** [comment]
all chunks have been downloaded, but display shows 2 green and 1 in progress

this immediatly corrects after refresh, so its only valid for new, previously unclicked files

**Comment by dnelband** [comment]
this what i see , checking with several videos: the number of the green bars is identical to the number of pieces in the piecesInfo array with status - "completed". can you please update, delete a video, and then reload it with the console panel open, and send me a print screen of your results?
![screen shot 2018-08-07 at 22 07 14](https://user-images.githubusercontent.com/5212537/43799959-37121416-9a8f-11e8-98c1-79ed96ea8bf8.png)

**Comment by haschimoto** [comment]
not done.
simple test:
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1Mz1_17uRwFQYo1RCDno3shrJv8mLcBKHLRrfpT_item_194+type:audio

looks like this:
![snap 2018-08-07 at 22 26 20](https://user-images.githubusercontent.com/20817185/43800603-21582924-9a91-11e8-982f-46306462cbbd.png)

**Comment by dnelband** [comment]
I’ve put the label by mistake, can u open the console panel , like i did in the example, expand the piecesInfo array (it has an arrow on the left), and send me the printscreen?

**Comment by haschimoto** [comment]
Can you load a very simple mp3 with 2 chunks and check yourself without
refresh?

**Comment by dnelband** [comment]
yeah sorry, i located the problem, i thought it was somewhere else.

**Comment by dnelband** [comment]
i've pushed a fix, please update & test, now i see the download bar loading from 0 - 100% smoothly and shows "file downloaded" only when everything is green

**Comment by haschimoto** [comment]
Yes, works!

**Comment by haschimoto** [comment]
Since you also corrected right-alt key, did you shrink cpcbox?

**Comment by haschimoto** [comment]
It doesnt work now anymore... its back to being 1 chunk behind.
