### ISSUE TITLE
cpcbox: shrink the emulator canvas

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#217]
it gets too big on a big screen, so lets make it smaller like the grey area was before and the shrunk area can be seen here:
![snap 2018-08-07 at 22 57 18](https://user-images.githubusercontent.com/20817185/43802210-65e54ee2-9a95-11e8-9818-82b0b2dbf79f.png)

**Comment by haschimoto** [comment]
about 70% from before... so also the stuff below can be easily seen plus the text for how to steer the emulator

**Comment by dnelband** [comment]
is this size ok?

**Comment by haschimoto** [comment]
:+1:
