### ISSUE TITLE
ZIP (game or archive): NO file over 1MB is d'loading any chunks, it is stuck at 0/x chunks after refresh

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#220]
e.g. GAME ZIP:
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1Mz1_1Ab8GRypvwkCYhjyPMP9mhbLvFymL4kSyE_item_6+type:game
![snap 2018-08-08 at 22 45 34](https://user-images.githubusercontent.com/20817185/43863545-54ad2604-9b5d-11e8-9a3f-8ee10e9a57f5.png)

or ARCHIVE ZIP:
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1Mz1_1Jz58PYy4dgxNX4QuPsnDpPQgF5UNvcEVx_item_35+type:archive
![snap 2018-08-08 at 22 47 27](https://user-images.githubusercontent.com/20817185/43863553-5d28399a-9b5d-11e8-9cf9-609be636d047.png)

any archive file of type zip that has not been loaded before seems to behave stuck.

**Comment by dnelband** [comment]
fixed:
1 - on upload interface, if file is zip, a select element is shown with "archive"/"game" options
2 - if user chooses game, a link with "select inner file" appears under the filename, and form will throw error if no inner file is specified
3 - after upload it is shown correctly

**Comment by haschimoto** [comment]
e.g. this:
/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1Mz1_1Ab8GRypvwkCYhjyPMP9mhbLvFymL4kSyE_item_3+type:archive

**Comment by dnelband** [comment]
archive files below 1MB (1 chunk) seem to behave normally - im able to open, view the files & download

the archive files the are BigFiles on my client have no peers, so i'm not sure if it doesnt download because of that or because of this bug.
i've signed & publish an updated version, i see that by you there are 5 peers to this, please try again

**Comment by haschimoto** [comment]
for big files ZIPs, it ALWAYS gives a bad error message, regardless if its defines as archive or game.
imo somewhere in the code, something checks and triggers the file immediately to be displayed as a ZIP file and ABORTS download.

**Comment by haschimoto** [comment]
just check if wolfpack zip game loads here:
https://0net.io/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?view:item+id:1_1C1gnFcVv9J9kUjF4odDMRYcEWVPJbbqFp_item_197+type:game

or gives bad ZIP error:
![snap 2018-08-09 at 20 57 39](https://user-images.githubusercontent.com/20817185/43919858-9b777b06-9c17-11e8-871e-caa55ae352c5.png)

**Comment by haschimoto** [comment]
0.6.3 rev3550 works
