### ISSUE TITLE
view: when file is missing, display "file not in cache... downloading XY MB now", add a spinner and place underneath each content viewer and load everything else while waiting

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#34]
1. load everything but the actual "javascript content viewer" part normal (sidebar, comments, etc.).

2. display the "File not found. Downloading..." part directly below or overlay the inactive js/emulator content viewer (similar how it was with nes emu, but now for all the same).

3. load or initialize the emulator or javascript viewer after confirmation the file has been downloaded fully in local cache.

That way it looks more pleasent while waiting.

**Comment by haschimoto** [comment]
eventually it will work, but seems very slow, so here is a suggestion:

lets load everything but the javascript content viewer part normally again (sidebar, comments, etc.) and display the "File not found. Downloading..." part directly below each js/emulator content window (similar how it was with nes emu, but now unified for all the same).
Then load the emulator or javascript viewer when confirmed the file has been available in local cache.
That way it looks more pleasent while waiting.
Also add again some animated idle spinner, since zeronet has many parts where one can wait while the window seems stuck/froze.

**Comment by dnelband** [comment]
add the "file not in cache" + spinner inside a gray overlay, which disappears when file is loaded into cache + player initiates. is that ok, or should i place it underneath an "empty" player?

**Comment by haschimoto** [comment]
looks good
can you change the blue for a white spinner there?
