### ISSUE TITLE
startpage: lets do only 1 row of 5 items and paging directly below for each filetype

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#35]
sorted by newest entries first from left to right, it would be 

Atari
latest 5 entries
paging

Amstrad
5 entries
paging

...

Videos
5 entries
paging

That way we can more quickly see new files and click through while staying at same height.

**Comment by dnelband** [comment]
new layout for home page ready for testing. restructuring created problem with current filter (channel / file type / media), working on solution.

**Comment by haschimoto** [comment]
Hi David: what do you mean by restructuring?
Global restructuring or only related to 5 item/row?

**Comment by dnelband** [comment]
no just something about how the items are rendered into different arrays on init. now its fixed
