### ISSUE TITLE
IFS ID

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#48]
Examples:

- id.kaffie.bit

or

- 0chan.bit/

![snap 2017-03-14 at 11 32 40](https://cloud.githubusercontent.com/assets/20817185/23896521/06d0e7b4-08aa-11e7-99bd-1e5ef08849ec.png)

**Comment by haschimoto** [comment]
@dnelband : 
any reason you didnt use it exactly like 0chn, that is 
sjkdghfkjshgd@ifs.anonymous
instead of 
alskdjhflksajhf@ifs.bit?

**Comment by dnelband** [comment]
no, sorry, i didnt understand that you want it @ifs.anonymous and i just used the naming conventions that seemed standard.
