### ISSUE TITLE
idea: an "all Clusters" page, where one can activate all clusters with one click

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#63]
Look here for zerome "all hubs" example:
https://bit.surf:43110/0hub.bit

**Comment by haschimoto** [comment]
where is it?

**Comment by dnelband** [comment]
its by the "all" heading on "all channels" - http://127.0.0.1:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:channels - the button with the label "seed all clusters" - 
which text should it contain / position should it be?

**Comment by haschimoto** [comment]
It could be called "Access to all Clusters of this server".

**Comment by haschimoto** [comment]
"Access to all clusters on this server" means only 2 clusters currently, but pressing the button shows to add 28 clusters:
![snap 2017-04-20 at 10 14 22](https://cloud.githubusercontent.com/assets/20817185/25220950/b49661d2-25b3-11e7-9290-38371d789be9.png)

@dnelband : reduce clusters to only the ACTIVE clusters and rename button.

**Comment by dnelband** [comment]
ok done
