### ISSUE TITLE
[browse]: add filter option in right upper corner: Moderation ON/OFF

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#72]
- default moderation is always ON
- ON: Filter all videos of hidden users
- OFF: show all videos

**Comment by haschimoto** [comment]
@dnelband : 
- make moderation ON/OFF a flip-switch
- place it in the upper right corner, but not in header, so it is BELOW the "0"

**Comment by dnelband** [comment]
is it ok now?

**Comment by slrslr** [comment]
@dnelband Hello, i see "Moderation" switch, but nowhere i can find what it really do. The FAQ is missing description and there is no tooltip when i hover mouse over it.
