### ISSUE TITLE
[video_viewer]: time remaining and progressed seem weird when skipping videos

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#74]
e.g.: /12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:4_1JdHwTT3WFmEH5WSoMhYeCGRBHqK6W9mjB_4+type:video

when you start it says 20:35min

when skipped in the middle, it says:
![snap 2017-04-22 at 12 14 28](https://cloud.githubusercontent.com/assets/20817185/25303535/495ecb7c-2755-11e7-8c6b-00bfa5b0f79b.png)

**Comment by haschimoto** [comment]
Dieses Video:
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:4_1JdHwTT3WFmEH5WSoMhYeCGRBHqK6W9mjB_4+type:video

ist nochmal dasselbe wie dieses:
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1EPjmmcfF8XU2itgtWLFSRrqgYdh7aUJ7W_1+type:video

**Comment by haschimoto** [comment]
the bug is that the video player is missing the HOUR FORMAT, it should be like 1:20:35 when starting

**Comment by dnelband** [comment]
sorry, i must have missed this ticket before you closed it. now its fixed.
