### ISSUE TITLE
[file names]: accept chinese chars (maybe even global chars)

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#77]
this could provide some info:
https://en.wikipedia.org/wiki/Internationalization_and_localization

**Comment by dnelband** [comment]
ive tried several times, saving a file with chinese characters works but unfortunately ZeroNet does not allow to sign & publish non Latin1 filenames for files. as a default temporary solution every file with a non Latin1 filename would be converted to a random alphanumeric string of 15 characters, to ensure filename uniqueness. ill write tamas about this and try to find better solutions.

**Comment by dnelband** [comment]
example - https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1xHs57rsaNTX2HKjCyF3G3dphHp8h9FpF_15+type:audio

**Comment by haschimoto** [comment]
using random chars for each chinese character seems okay for now.
