### ISSUE TITLE
startpage: it says 29 games, but Page 3 shows FULL row of ten games=30

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#81]
also , it seems the last page lists 1 game multiple times:
![snap 2017-04-24 at 08 52 35](https://cloud.githubusercontent.com/assets/20817185/25325354/7b58be72-28cb-11e7-9fab-2adc125b3f5c.png)

**Comment by dnelband** [comment]
ok fixed

**Comment by haschimoto** [comment]
What happened? Why is MUDS no longer there??

**Comment by dnelband** [comment]
ive deleted some files to understand why everything was doubled. the reason was 2 clusters that ive cloned wrong and forgot to remove the IFS MERGER TYPE from their content.json.

now ive uploaded the games again
