### ISSUE TITLE
[video_viewer]: doesnt show MP4 video, because internally its an FLV format

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#82]
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1EPjmmcfF8XU2itgtWLFSRrqgYdh7aUJ7W_1+type:video

**Comment by haschimoto** [comment]
same with this MP4:
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1A5Uw4pejzgKx4c3yZkz8whBcqMaypp1Wo_3+type:video

**Comment by haschimoto** [comment]
![snap 2017-04-24 at 18 32 53](https://cloud.githubusercontent.com/assets/20817185/25347828/7378db46-291c-11e7-92d0-7de5c334d5cb.png)

**Comment by dnelband** [comment]
i've tried to reupload this video (because it is downloaded and is physically there) but also after multiple retries with different names it still doesnt work. i think its about the specific file.

**Comment by haschimoto** [comment]
ah yes, its an FLV file which someone renamed to mp4... now maybe we can also play FLV in js-player?
