### ISSUE TITLE
[upload]; prevent adding unsupported filetypes: .MKV

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#84]
since we cannot play MKV, prevent uploading such a filetype
Also, if we cannot play FLV files, prevent uploading those too.

**Comment by dnelband** [comment]
ok, now there is a list of supported file types in content/config.json - 
"file_types":["avi","bin","epub","gif","jpeg","jpg","mp3","mp4","nes","ogg","png","sna","wav","webm","zip"].
if file_type of file does not match any of the file_types option then an error is shown: "file type [FILE_TYPE] is not supported".

is this ok?

**Comment by haschimoto** [comment]
looks okay, does FLV also work?

**Comment by dnelband** [comment]
unfortunately not

**Comment by haschimoto** [comment]
okay
