### ISSUE TITLE
[double video seems not to play]

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#85]
Dieses Video:
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:4_1JdHwTT3WFmEH5WSoMhYeCGRBHqK6W9mjB_4+type:video

sieht aus wie nochmal dasselbe wie dieses:
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1EPjmmcfF8XU2itgtWLFSRrqgYdh7aUJ7W_1+type:video

Das obere ist unter "Browse", aber kann gar nicht abgespielt werden!
Das untere ist MODERATED, funktioniert aber!
Beide haben ca. 142Peers und selbe länge aber DAS UNTERE ist das funcktionierende, und sollte auch erhalten bleiben mit Kommentaren, Votes etc.

**Comment by haschimoto** [comment]
Das untere ist MODERATED, d.h. gefiltert.
Das interessante ist jedoch, dass es wohl dasselbe Video ist, es ist diesselbe Datei? Es sind zumindest dieselben Peers.
Bitte diesen Channel wieder einblenden und dann untersuchen, warum es 2 Einträge gibt:
![snap 2017-04-25 at 12 03 15](https://cloud.githubusercontent.com/assets/20817185/25380177/a41dd6f0-29af-11e7-85b7-42377f24fdd9.png)
![snap 2017-04-25 at 12 05 01](https://cloud.githubusercontent.com/assets/20817185/25380181/a6ef78a2-29af-11e7-9991-fb6e9b50eeb6.png)

**Comment by dnelband** [comment]
1 - das funktionierende Video war nicht beim Browse angezeigt weil den User (i.e seine ganze channels) ausmoderiert war (das ist der User der die spam hochgeladen hat)

2 - die videos sind nicht dasselbe files (also, zwei verschiedenen file names & file paths). das funktionierende ist 4 tage alt und hat "123.mp4" als filename, das nicht funktionierende hat ein random filename - "p6VsligeS6sbLsJ.mp4"

3 -  ich vermüte dass es nicht funktioniert wegen der Großebuchstabe im filename. also es hat bei mir local den nichtfunktionierenden Video sogar nicht heruntergeladen. außerdem größen Buchstaben kann ich nicht erklären warum das andere video doch funktioniert und dieses nicht

4 - ich hab es verändert dass auch random generierete filenammen werden toLowerCase convertiert beim hochladen.

**Comment by dnelband** [comment]
was passiert, wahrschienlich, ist dass nachdem ich die channels des users ausmoderiert habe, er hat unter einer anderen username & channel das video mit anderer filename hochgeladen, und das hat nicht funktioniert wegen der filename

**Comment by haschimoto** [comment]
wegen dem GROSSbuchstaben?

Hier ist ein Video mit filename mit GROSSbuchstaben:
12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1CeQ5jrL4dgi6A2NnWZLymYvZWkm3sYxsz_31+type:video

**Comment by haschimoto** [comment]
> 4 - ich hab es verändert dass auch random generierete filenammen werden toLowerCase convertiert beim hochladen.
Wenn Grossbuchstaben funktionieren, dann müssen wir nicht unbedingt alles toLowerCase konvertieren?
