### ISSUE TITLE
if a file can no longer be found via link, show a 404 error message

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#86]
Example: https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:1_1EPjmmcfF8XU2itgtWLFSRrqgYdh7aUJ7W_1+type:video

Now its just showing white space, I have an idea for a 404 message (we can even have more than one and show random ones if we have good ideas)

**Comment by haschimoto** [comment]
black background +
![ive-seen-things](https://cloud.githubusercontent.com/assets/20817185/25497997/a087cfea-2b86-11e7-85be-70432af000a3.png)

**Comment by haschimoto** [comment]
great! just the bottom is still white, it looks like this:
![snap 2017-04-28 at 22 04 05](https://cloud.githubusercontent.com/assets/20817185/25545339/ad288d9c-2c5e-11e7-8109-03fea9eb6cf4.png)


How about also making the image smaller though, like 50%?

**Comment by dnelband** [comment]
ok done
