### ISSUE TITLE
cluster switch: should be turned OFF default, some polish

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#89]
![snap 2017-04-28 at 18 27 07](https://cloud.githubusercontent.com/assets/20817185/25537810/561c3eb8-2c40-11e7-81d5-d5eb373eed5e.png)

- turn switch OFF default
- change text "Help distribute all files"
- align switch to right side before "Total"
- rename "Total: " to "Channels: "

**Comment by dnelband** [comment]
done. example: https://zn.maly.io/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:channels
if you have it on it means youre distributing, so turn it off & refresh to see it as default.

**Comment by haschimoto** [comment]
awesome!
