### ISSUE TITLE
[viewer]: cudas "9" video doesnt load

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#91]
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:2_18Tac6A6tQLGhLRXbP7FafhV7NRbxaboVe_1+type:video

third video in this screenshot from bitsurf:
![snap 2017-04-29 at 17 40 19](https://cloud.githubusercontent.com/assets/20817185/25556758/fa1e94d0-2d02-11e7-838a-c47e4f1de8a2.png)

**Comment by haschimoto** [comment]
there only comes a blank screenn, not even trying to download the video since the file missing:
![snap 2017-04-28 at 22 12 28](https://cloud.githubusercontent.com/assets/20817185/25545588/daf3347e-2c5f-11e7-8645-8867fcc1b4ea.png)

**Comment by haschimoto** [comment]
also happens for video named "9" in the above screenshot

**Comment by haschimoto** [comment]
"xi" video showed missing file - downloading and worked fine:
![snap 2017-04-28 at 22 14 10](https://cloud.githubusercontent.com/assets/20817185/25545656/15a96822-2c60-11e7-9ca6-57d5c9dcfaa8.png)

**Comment by dnelband** [comment]
i cant load that file either, and looking in the user directory in the cluster i can see its not even downloaded

**Comment by haschimoto** [comment]
Then why doesnt it display "file not found - trying to download"?

**Comment by haschimoto** [comment]
Hmm, the "9" video doesnt even show a download file when hovering over the link:
https://zn.maly.io/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:item+id:2_18Tac6A6tQLGhLRXbP7FafhV7NRbxaboVe_1+type:video

**Comment by haschimoto** [comment]
I suggest to look into the cluster and see what the file is supposed to be named and why it may be not loading/missing/playing
