### ISSUE TITLE
[CREATE CHANNEL]: IMMEDIATELY REMOVE the "Create Channel" window after pressing "Create Channel" Button to PREVENT trigger it MULTIPLE times

### ISSUE THREAD

**Issue by haschimoto** [zer0net/ifs-master#95]
the "create channel" button from here got triggered 3xtimes:
![snap 2017-04-30 at 10 49 42](https://cloud.githubusercontent.com/assets/20817185/25563023/4d19f68a-2d93-11e7-9371-fa2253ee42c5.png)

resulted in this:
![snap 2017-04-30 at 10 51 01](https://cloud.githubusercontent.com/assets/20817185/25563133/9111d7a2-2d95-11e7-8a3e-2ec1f1c6108d.png)

**Comment by haschimoto** [comment]
so now the same channel "exists" 3 times, but all under the same adress (note that clicking a channel link doesnt work anymore and shows the startpage because of the other ticket):
https://bit.surf:43110/12MVkvYGcRW6u2NYbpfwVad1oQeyG4s9Er/index.html?route:main+id:3_1R67TfYzNkCnh89EFfGmXn5LMb4hXaMRQ
![snap 2017-04-30 at 11 06 43](https://cloud.githubusercontent.com/assets/20817185/25563121/33842536-2d95-11e7-9e6f-284a3ef9047b.png)

also any item uploaded will get added on all three "instances" and hence appear 3xtimes on startpage:
![snap 2017-04-30 at 11 11 48](https://cloud.githubusercontent.com/assets/20817185/25563148/d83b9b4a-2d95-11e7-831d-6c6298e857f7.png)

**Comment by haschimoto** [comment]
update:
i fixed it now manually by removing 2 of the entries in the data.json and republish it, but the tickets topic to immediately close the window popup to prevent triggering still should be solved.

**Comment by dnelband** [comment]
closing the popup results in scope issues, instead i've replace the content with a loader + message "creating channel", is that ok?
